/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */
/* Table schema:
CREATE TABLE kv_store_16400ba4 (
  key TEXT NOT NULL PRIMARY KEY,
  value JSONB NOT NULL
);
*/
import { createClient } from "jsr:@supabase/supabase-js@2.49.8";

const client = () =>
  createClient(
    Deno.env.get("SUPABASE_URL")!,
    Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!,
  );

export const set = async (key: string, value: unknown) => {
  const { error } = await client().from("kv_store_16400ba4").upsert({ key, value });
  if (error) throw new Error(error.message);
};

export const get = async (key: string): Promise<any> => {
  const { data, error } = await client()
    .from("kv_store_16400ba4").select("value").eq("key", key).maybeSingle();
  if (error) throw new Error(error.message);
  return data?.value;
};

export const del = async (key: string) => {
  const { error } = await client().from("kv_store_16400ba4").delete().eq("key", key);
  if (error) throw new Error(error.message);
};

export const mset = async (keys: string[], values: unknown[]) => {
  const { error } = await client()
    .from("kv_store_16400ba4")
    .upsert(keys.map((k, i) => ({ key: k, value: values[i] })));
  if (error) throw new Error(error.message);
};

export const mget = async (keys: string[]): Promise<any[]> => {
  const { data, error } = await client()
    .from("kv_store_16400ba4").select("value").in("key", keys);
  if (error) throw new Error(error.message);
  return data?.map((d) => d.value) ?? [];
};

export const mdel = async (keys: string[]) => {
  const { error } = await client().from("kv_store_16400ba4").delete().in("key", keys);
  if (error) throw new Error(error.message);
};

export const getByPrefix = async (prefix: string): Promise<any[]> => {
  const { data, error } = await client()
    .from("kv_store_16400ba4").select("key, value").like("key", prefix + "%");
  if (error) throw new Error(error.message);
  return data?.map((d) => d.value) ?? [];
};
