/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "ekfhnbdiqufxbarbbsyf"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVrZmhuYmRpcXVmeGJhcmJic3lmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzk2MzU1OTAsImV4cCI6MjA5NTIxMTU5MH0.Q5Q0_baxXR2LkeX7-I0LF4_3zScJD9YtRNI0Py4k-ow"